import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🚀 Starting AdTech Quiz seed (Part 2)...');
  console.log('📝 Adding questions 121-241...\n');

  // Questions 121-241
  const questions = [
    // Continuing Mediums (121-125)
    { id: 'mediums_q14', quizId: 'quiz-mediums', text: 'What is shoppable advertising?', options: JSON.stringify([{ id: 'a', text: 'Ads that allow users to purchase products directly without leaving the ad', isCorrect: true }, { id: 'b', text: 'Ads for shopping centers', isCorrect: false }, { id: 'c', text: 'Discount advertising', isCorrect: false }, { id: 'd', text: 'Price comparison ads', isCorrect: false }]), explanation: 'Shoppable ads enable users to browse and purchase products directly within the ad experience without navigating to a separate website.', order: 121, points: 10 },
    { id: 'mediums_q15', quizId: 'quiz-mediums', text: 'What is podcast advertising?', options: JSON.stringify([{ id: 'a', text: 'Audio ads delivered before, during, or after podcast content', isCorrect: true }, { id: 'b', text: 'Podcasts about advertising', isCorrect: false }, { id: 'c', text: 'Advertising podcast equipment', isCorrect: false }, { id: 'd', text: 'Podcast subscription promotions', isCorrect: false }]), explanation: 'Podcast advertising includes host-read and pre-produced audio ads inserted into podcast content, often highly engaged by loyal listeners.', order: 122, points: 10 },
    { id: 'mediums_q16', quizId: 'quiz-mediums', text: 'What is influencer marketing in digital advertising?', options: JSON.stringify([{ id: 'a', text: 'Partnering with social media personalities to promote products to their followers', isCorrect: true }, { id: 'b', text: 'Marketing to influential business executives', isCorrect: false }, { id: 'c', text: 'Influencing market prices', isCorrect: false }, { id: 'd', text: 'Political advertising', isCorrect: false }]), explanation: 'Influencer marketing involves partnering with individuals who have dedicated social followings to promote products through authentic content.', order: 123, points: 10 },
    
    // Continuing Ad Serving (124-130)
    { id: 'adserving_q9', quizId: 'quiz-adserving', text: 'What is passback in ad serving?', options: JSON.stringify([{ id: 'a', text: 'Sending an unfilled ad request to another ad server or network', isCorrect: true }, { id: 'b', text: 'Returning an ad to the advertiser', isCorrect: false }, { id: 'c', text: 'Passing user data backwards', isCorrect: false }, { id: 'd', text: 'A failed ad delivery', isCorrect: false }]), explanation: 'A passback occurs when an ad server cannot fill a request and passes it to another server or network for a second chance at monetization.', order: 124, points: 10 },
    { id: 'adserving_q10', quizId: 'quiz-adserving', text: 'What is ad blocking?', options: JSON.stringify([{ id: 'a', text: 'Software that prevents ads from being displayed to users', isCorrect: true }, { id: 'b', text: 'Blocking competitor ads', isCorrect: false }, { id: 'c', text: 'Server-side ad filtering', isCorrect: false }, { id: 'd', text: 'Pausing ad campaigns', isCorrect: false }]), explanation: 'Ad blocking uses browser extensions or software to prevent advertisements from being displayed, affecting publisher revenue and advertiser reach.', order: 125, points: 10 },
    { id: 'adserving_q11', quizId: 'quiz-adserving', text: 'What is a default ad?', options: JSON.stringify([{ id: 'a', text: 'A fallback ad shown when no paid ad is available', isCorrect: true }, { id: 'b', text: 'The first ad in a campaign', isCorrect: false }, { id: 'c', text: 'Standard ad sizes', isCorrect: false }, { id: 'd', text: 'Factory preset ads', isCorrect: false }]), explanation: 'A default ad is a fallback advertisement shown when the ad server cannot find a paid ad that matches the request criteria.', order: 126, points: 10 },
    { id: 'adserving_q12', quizId: 'quiz-adserving', text: 'What is competitive separation?', options: JSON.stringify([{ id: 'a', text: 'Preventing competitor ads from appearing on the same page', isCorrect: true }, { id: 'b', text: 'Separating ad budgets by competitor', isCorrect: false }, { id: 'c', text: 'Competitive market analysis', isCorrect: false }, { id: 'd', text: 'Pricing competition prevention', isCorrect: false }]), explanation: 'Competitive separation ensures ads from competing brands do not appear on the same page or within the same ad break.', order: 127, points: 10 },
    
    // Continuing Targeting (128-140)
    { id: 'targeting_q9', quizId: 'quiz-targeting', text: 'What is audience suppression?', options: JSON.stringify([{ id: 'a', text: 'Excluding certain users from seeing your ads', isCorrect: true }, { id: 'b', text: 'Reducing audience size', isCorrect: false }, { id: 'c', text: 'Suppressing competition', isCorrect: false }, { id: 'd', text: 'Limiting audience feedback', isCorrect: false }]), explanation: 'Audience suppression excludes certain users (like existing customers) from ad targeting to focus budget on new customer acquisition.', order: 128, points: 10 },
    { id: 'targeting_q10', quizId: 'quiz-targeting', text: 'What is sequential messaging?', options: JSON.stringify([{ id: 'a', text: 'Showing users a series of ads in a specific order', isCorrect: true }, { id: 'b', text: 'Numbering ad creatives', isCorrect: false }, { id: 'c', text: 'Following up with emails', isCorrect: false }, { id: 'd', text: 'Sequential budget allocation', isCorrect: false }]), explanation: 'Sequential messaging delivers a series of ads to users in a specific order, telling a story or guiding them through the funnel.', order: 129, points: 10 },
    { id: 'targeting_q11', quizId: 'quiz-targeting', text: 'What is weather targeting?', options: JSON.stringify([{ id: 'a', text: 'Serving ads based on local weather conditions', isCorrect: true }, { id: 'b', text: 'Advertising weather apps', isCorrect: false }, { id: 'c', text: 'Seasonal advertising only', isCorrect: false }, { id: 'd', text: 'Weatherproofing ad campaigns', isCorrect: false }]), explanation: 'Weather targeting uses real-time weather data to serve contextually relevant ads, like promoting umbrellas when it is raining.', order: 130, points: 10 },
    { id: 'targeting_q12', quizId: 'quiz-targeting', text: 'What is intent targeting?', options: JSON.stringify([{ id: 'a', text: 'Targeting users based on signals indicating purchase intent', isCorrect: true }, { id: 'b', text: 'Targeting intentional clickers', isCorrect: false }, { id: 'c', text: 'Intended audience reach', isCorrect: false }, { id: 'd', text: 'Targeting by intention to leave site', isCorrect: false }]), explanation: 'Intent targeting reaches users who have shown signals of purchase intent through search queries, content consumption, or other behaviors.', order: 131, points: 10 },
    { id: 'targeting_q13', quizId: 'quiz-targeting', text: 'What is conquest targeting?', options: JSON.stringify([{ id: 'a', text: 'Targeting users who have shown interest in competitor brands', isCorrect: true }, { id: 'b', text: 'Military advertising strategy', isCorrect: false }, { id: 'c', text: 'Aggressive bidding tactics', isCorrect: false }, { id: 'd', text: 'Market domination campaigns', isCorrect: false }]), explanation: 'Conquest targeting specifically reaches users who have engaged with competitor brands, aiming to win them over.', order: 132, points: 10 },
    { id: 'targeting_q14', quizId: 'quiz-targeting', text: 'What is custom affinity audiences?', options: JSON.stringify([{ id: 'a', text: 'User-defined audience segments based on interests and behaviors', isCorrect: true }, { id: 'b', text: 'Audiences with similar appearances', isCorrect: false }, { id: 'c', text: 'Customized affiliate programs', isCorrect: false }, { id: 'd', text: 'Predetermined audience groups', isCorrect: false }]), explanation: 'Custom affinity audiences allow advertisers to create their own interest-based segments using URLs, keywords, and apps that define their ideal customer.', order: 133, points: 10 },
    { id: 'targeting_q15', quizId: 'quiz-targeting', text: 'What is in-market audiences?', options: JSON.stringify([{ id: 'a', text: 'Users actively researching or planning to purchase products/services', isCorrect: true }, { id: 'b', text: 'Users currently in a marketplace', isCorrect: false }, { id: 'c', text: 'Market research participants', isCorrect: false }, { id: 'd', text: 'Users in marketing roles', isCorrect: false }]), explanation: 'In-market audiences are users who are actively researching or comparing products and services, showing high purchase intent.', order: 134, points: 10 },
    
    // Continuing Tracking (135-141)
    { id: 'tracking_q9', quizId: 'quiz-tracking', text: 'What is post-click tracking?', options: JSON.stringify([{ id: 'a', text: 'Tracking user actions after they click on an ad', isCorrect: true }, { id: 'b', text: 'Tracking failed clicks', isCorrect: false }, { id: 'c', text: 'Postal mail tracking', isCorrect: false }, { id: 'd', text: 'After-campaign analysis', isCorrect: false }]), explanation: 'Post-click tracking monitors user behavior and actions after clicking on an ad, measuring engagement and conversions on the landing page.', order: 135, points: 10 },
    { id: 'tracking_q10', quizId: 'quiz-tracking', text: 'What is server-side tracking?', options: JSON.stringify([{ id: 'a', text: 'Tracking implemented on the server rather than in the browser', isCorrect: true }, { id: 'b', text: 'Tracking server performance', isCorrect: false }, { id: 'c', text: 'Server room monitoring', isCorrect: false }, { id: 'd', text: 'Tracking hosting costs', isCorrect: false }]), explanation: 'Server-side tracking processes conversion data on the server, offering more reliability and privacy compliance than client-side tracking.', order: 136, points: 10 },
    { id: 'tracking_q11', quizId: 'quiz-tracking', text: 'What is event tracking?', options: JSON.stringify([{ id: 'a', text: 'Monitoring specific user interactions like button clicks and form submissions', isCorrect: true }, { id: 'b', text: 'Tracking event attendance', isCorrect: false }, { id: 'c', text: 'Calendar event monitoring', isCorrect: false }, { id: 'd', text: 'Live event streaming analytics', isCorrect: false }]), explanation: 'Event tracking monitors specific user interactions on a website or app, such as button clicks, video plays, and form submissions.', order: 137, points: 10 },
    { id: 'tracking_q12', quizId: 'quiz-tracking', text: 'What is a data layer?', options: JSON.stringify([{ id: 'a', text: 'A JavaScript object that stores data for tag management systems', isCorrect: true }, { id: 'b', text: 'A database storage tier', isCorrect: false }, { id: 'c', text: 'A network layer for data', isCorrect: false }, { id: 'd', text: 'Visual data representation', isCorrect: false }]), explanation: 'A data layer is a JavaScript object that stores and organizes data about user interactions for use by tag management systems and analytics tools.', order: 138, points: 10 },
    { id: 'tracking_q13', quizId: 'quiz-tracking', text: 'What is engagement rate?', options: JSON.stringify([{ id: 'a', text: 'The percentage of users who interact with content beyond just viewing', isCorrect: true }, { id: 'b', text: 'Marriage proposal statistics', isCorrect: false }, { id: 'c', text: 'Employee engagement scores', isCorrect: false }, { id: 'd', text: 'Contract engagement terms', isCorrect: false }]), explanation: 'Engagement rate measures the percentage of users who actively interact with content through likes, shares, comments, or clicks beyond passive viewing.', order: 139, points: 10 },
    { id: 'tracking_q14', quizId: 'quiz-tracking', text: 'What is bounce rate?', options: JSON.stringify([{ id: 'a', text: 'The percentage of visitors who leave after viewing only one page', isCorrect: true }, { id: 'b', text: 'Email bounce rate', isCorrect: false }, { id: 'c', text: 'Ad rejection rate', isCorrect: false }, { id: 'd', text: 'Server error rate', isCorrect: false }]), explanation: 'Bounce rate is the percentage of visitors who leave a website after viewing only one page without taking any further action.', order: 140, points: 10 },
    { id: 'tracking_q15', quizId: 'quiz-tracking', text: 'What is dwell time?', options: JSON.stringify([{ id: 'a', text: 'The amount of time a user spends viewing content or an ad', isCorrect: true }, { id: 'b', text: 'Time before ad loads', isCorrect: false }, { id: 'c', text: 'Server response time', isCorrect: false }, { id: 'd', text: 'Campaign duration', isCorrect: false }]), explanation: 'Dwell time measures how long a user spends viewing content or an ad, indicating engagement level and interest.', order: 141, points: 10 },
    
    // Continuing Media Buying (142-148)
    { id: 'mediabuying_q9', quizId: 'quiz-mediabuying', text: 'What is preferred deals?', options: JSON.stringify([{ id: 'a', text: 'Fixed-price agreements giving advertisers first access to premium inventory', isCorrect: true }, { id: 'b', text: 'Discounted ad rates', isCorrect: false }, { id: 'c', text: 'Preferred customer pricing', isCorrect: false }, { id: 'd', text: 'Best-performing deals', isCorrect: false }]), explanation: 'Preferred deals are fixed-price agreements where advertisers get first look at premium inventory before it goes to auction.', order: 142, points: 10 },
    { id: 'mediabuying_q10', quizId: 'quiz-mediabuying', text: 'What is curated marketplace?', options: JSON.stringify([{ id: 'a', text: 'A pre-selected package of inventory from multiple publishers', isCorrect: true }, { id: 'b', text: 'An art gallery ad network', isCorrect: false }, { id: 'c', text: 'Manually selected ad placements', isCorrect: false }, { id: 'd', text: 'A museum advertising platform', isCorrect: false }]), explanation: 'A curated marketplace offers pre-selected inventory packages from multiple publishers, often organized by theme, audience, or quality tier.', order: 143, points: 10 },
    { id: 'mediabuying_q11', quizId: 'quiz-mediabuying', text: 'What is insertion order (IO)?', options: JSON.stringify([{ id: 'a', text: 'A formal agreement between buyer and seller specifying campaign details', isCorrect: true }, { id: 'b', text: 'The order ads are inserted on page', isCorrect: false }, { id: 'c', text: 'Database insert commands', isCorrect: false }, { id: 'd', text: 'Ad placement sequence', isCorrect: false }]), explanation: 'An insertion order is a formal contract between advertiser and publisher detailing campaign specifications, pricing, and delivery terms.', order: 144, points: 10 },
    { id: 'mediabuying_q12', quizId: 'quiz-mediabuying', text: 'What is make-good?', options: JSON.stringify([{ id: 'a', text: 'Compensation given when a publisher under-delivers on contracted impressions', isCorrect: true }, { id: 'b', text: 'Creating good ads', isCorrect: false }, { id: 'c', text: 'Brand reputation repair', isCorrect: false }, { id: 'd', text: 'Quality improvement process', isCorrect: false }]), explanation: 'A make-good is compensation (additional impressions or refund) when a publisher fails to deliver the contracted number of impressions.', order: 145, points: 10 },
    { id: 'mediabuying_q13', quizId: 'quiz-mediabuying', text: 'What is agency commission?', options: JSON.stringify([{ id: 'a', text: 'The fee or percentage an agency charges for media buying services', isCorrect: true }, { id: 'b', text: 'Commission for ad sales', isCorrect: false }, { id: 'c', text: 'Publisher referral fees', isCorrect: false }, { id: 'd', text: 'Creative development fees', isCorrect: false }]), explanation: 'Agency commission is the fee or percentage that advertising agencies charge clients for their media planning and buying services.', order: 146, points: 10 },
    { id: 'mediabuying_q14', quizId: 'quiz-mediabuying', text: 'What is upfront buying?', options: JSON.stringify([{ id: 'a', text: 'Purchasing ad inventory in advance, often at discounted rates', isCorrect: true }, { id: 'b', text: 'Paying before ad delivery', isCorrect: false }, { id: 'c', text: 'Front-page ad placement', isCorrect: false }, { id: 'd', text: 'Priority bidding', isCorrect: false }]), explanation: 'Upfront buying involves purchasing ad inventory in advance (often annually for TV), typically at better rates in exchange for commitment.', order: 147, points: 10 },
    { id: 'mediabuying_q15', quizId: 'quiz-mediabuying', text: 'What is scatter market?', options: JSON.stringify([{ id: 'a', text: 'Purchasing ad inventory closer to air date, often at higher rates', isCorrect: true }, { id: 'b', text: 'Scattered ad placements', isCorrect: false }, { id: 'c', text: 'Market fragmentation', isCorrect: false }, { id: 'd', text: 'Diverse audience targeting', isCorrect: false }]), explanation: 'Scatter market refers to purchasing inventory closer to air date rather than upfront, typically at higher rates but with more flexibility.', order: 148, points: 10 },
    
    // Continuing User ID (149-154)
    { id: 'userid_q9', quizId: 'quiz-userid', text: 'What is a deterministic ID?', options: JSON.stringify([{ id: 'a', text: 'An identifier based on known, verified user information like email', isCorrect: true }, { id: 'b', text: 'A predetermined user ID', isCorrect: false }, { id: 'c', text: 'A fixed system ID', isCorrect: false }, { id: 'd', text: 'A database primary key', isCorrect: false }]), explanation: 'A deterministic ID is based on known, verified user information like email addresses or login credentials, providing high accuracy.', order: 149, points: 10 },
    { id: 'userid_q10', quizId: 'quiz-userid', text: 'What is Unified ID 2.0?', options: JSON.stringify([{ id: 'a', text: 'An industry initiative for privacy-conscious identity using hashed emails', isCorrect: true }, { id: 'b', text: 'A second version of universal IDs', isCorrect: false }, { id: 'c', text: 'A unified database system', isCorrect: false }, { id: 'd', text: 'A standard ID card format', isCorrect: false }]), explanation: 'Unified ID 2.0 is an open-source identity framework that creates encrypted, privacy-conscious IDs from hashed email addresses.', order: 150, points: 10 },
    { id: 'userid_q11', quizId: 'quiz-userid', text: 'What is ID bridging?', options: JSON.stringify([{ id: 'a', text: 'Connecting different user identifiers across platforms and devices', isCorrect: true }, { id: 'b', text: 'Building network bridges', isCorrect: false }, { id: 'c', text: 'Bridging payment systems', isCorrect: false }, { id: 'd', text: 'Connecting ad networks', isCorrect: false }]), explanation: 'ID bridging connects different user identifiers across platforms and devices to create a more complete view of user behavior.', order: 151, points: 10 },
    { id: 'userid_q12', quizId: 'quiz-userid', text: 'What is an identity graph?', options: JSON.stringify([{ id: 'a', text: 'A database linking multiple identifiers to a single user profile', isCorrect: true }, { id: 'b', text: 'A graphical ID display', isCorrect: false }, { id: 'c', text: 'User identity visualization', isCorrect: false }, { id: 'd', text: 'A social network map', isCorrect: false }]), explanation: 'An identity graph is a database that links multiple identifiers (cookies, device IDs, emails) to create unified user profiles.', order: 152, points: 10 },
    { id: 'userid_q13', quizId: 'quiz-userid', text: 'What is authenticated traffic?', options: JSON.stringify([{ id: 'a', text: 'Traffic from users who are logged in with verified identities', isCorrect: true }, { id: 'b', text: 'Verified non-bot traffic', isCorrect: false }, { id: 'c', text: 'Secure encrypted traffic', isCorrect: false }, { id: 'd', text: 'Premium traffic sources', isCorrect: false }]), explanation: 'Authenticated traffic comes from users who are logged into a website or app, providing verified identity information for targeting.', order: 153, points: 10 },
    { id: 'userid_q14', quizId: 'quiz-userid', text: 'What is contextual identity?', options: JSON.stringify([{ id: 'a', text: 'Inferring user interests from content consumption without tracking individuals', isCorrect: true }, { id: 'b', text: 'Identity based on context clues', isCorrect: false }, { id: 'c', text: 'Situational user targeting', isCorrect: false }, { id: 'd', text: 'Context-aware applications', isCorrect: false }]), explanation: 'Contextual identity infers user interests from the content they consume in real-time without relying on persistent identifiers or tracking.', order: 154, points: 10 },
    
    // Continuing Data (155-162)
    { id: 'data_q9', quizId: 'quiz-data', text: 'What is zero-party data?', options: JSON.stringify([{ id: 'a', text: 'Data intentionally and proactively shared by customers', isCorrect: true }, { id: 'b', text: 'Data with zero cost', isCorrect: false }, { id: 'c', text: 'Anonymous data', isCorrect: false }, { id: 'd', text: 'Empty data fields', isCorrect: false }]), explanation: 'Zero-party data is information that customers intentionally and proactively share with a brand, such as preferences, intentions, and personal context.', order: 155, points: 10 },
    { id: 'data_q10', quizId: 'quiz-data', text: 'What is data deprecation?', options: JSON.stringify([{ id: 'a', text: 'The phasing out of traditional data collection methods like third-party cookies', isCorrect: true }, { id: 'b', text: 'Data value decrease', isCorrect: false }, { id: 'c', text: 'Data deletion process', isCorrect: false }, { id: 'd', text: 'Outdated data removal', isCorrect: false }]), explanation: 'Data deprecation refers to the phasing out of traditional data collection methods, particularly third-party cookies and device identifiers.', order: 156, points: 10 },
    { id: 'data_q11', quizId: 'quiz-data', text: 'What is data portability?', options: JSON.stringify([{ id: 'a', text: 'The ability for users to obtain and transfer their personal data', isCorrect: true }, { id: 'b', text: 'Portable storage devices', isCorrect: false }, { id: 'c', text: 'Mobile data collection', isCorrect: false }, { id: 'd', text: 'Data backup systems', isCorrect: false }]), explanation: 'Data portability is a privacy right allowing users to obtain their personal data in a structured format and transfer it to another service.', order: 157, points: 10 },
    { id: 'data_q12', quizId: 'quiz-data', text: 'What is data minimization?', options: JSON.stringify([{ id: 'a', text: 'Collecting only the data necessary for a specific purpose', isCorrect: true }, { id: 'b', text: 'Reducing data storage costs', isCorrect: false }, { id: 'c', text: 'Compressing data files', isCorrect: false }, { id: 'd', text: 'Minimizing data errors', isCorrect: false }]), explanation: 'Data minimization is a privacy principle requiring organizations to collect only the minimum personal data necessary for a specific purpose.', order: 158, points: 10 },
    { id: 'data_q13', quizId: 'quiz-data', text: 'What is purpose limitation?', options: JSON.stringify([{ id: 'a', text: 'Using collected data only for the purposes disclosed to users', isCorrect: true }, { id: 'b', text: 'Limiting data analysis', isCorrect: false }, { id: 'c', text: 'Restricting data storage', isCorrect: false }, { id: 'd', text: 'Limiting data access', isCorrect: false }]), explanation: 'Purpose limitation is a privacy principle requiring that personal data be collected for specified purposes and not used for incompatible purposes.', order: 159, points: 10 },
    { id: 'data_q14', quizId: 'quiz-data', text: 'What is differential privacy?', options: JSON.stringify([{ id: 'a', text: 'A mathematical framework adding noise to data to protect individual privacy', isCorrect: true }, { id: 'b', text: 'Different privacy settings', isCorrect: false }, { id: 'c', text: 'Varied privacy policies', isCorrect: false }, { id: 'd', text: 'Comparing privacy levels', isCorrect: false }]), explanation: 'Differential privacy is a mathematical framework that adds statistical noise to datasets, allowing analysis while protecting individual privacy.', order: 160, points: 10 },
    { id: 'data_q15', quizId: 'quiz-data', text: 'What is federated learning?', options: JSON.stringify([{ id: 'a', text: 'Machine learning that trains on decentralized data without sharing raw data', isCorrect: true }, { id: 'b', text: 'Federal government data programs', isCorrect: false }, { id: 'c', text: 'Federated database systems', isCorrect: false }, { id: 'd', text: 'Collaborative learning platforms', isCorrect: false }]), explanation: 'Federated learning trains machine learning models across decentralized devices holding local data, without sharing raw data with a central server.', order: 161, points: 10 },
    { id: 'data_q16', quizId: 'quiz-data', text: 'What is TCF (Transparency and Consent Framework)?', options: JSON.stringify([{ id: 'a', text: 'IAB Europe standard for managing GDPR consent in digital advertising', isCorrect: true }, { id: 'b', text: 'Technology Certification Framework', isCorrect: false }, { id: 'c', text: 'Tracking Control Features', isCorrect: false }, { id: 'd', text: 'Technical Compliance Format', isCorrect: false }]), explanation: 'TCF is IAB Europe standardized framework for managing and communicating user consent for data processing in digital advertising.', order: 162, points: 10 },
    
    // Continuing Attribution (163-169)
    { id: 'attribution_q9', quizId: 'quiz-attribution', text: 'What is fractional attribution?', options: JSON.stringify([{ id: 'a', text: 'Distributing conversion credit as fractions across multiple touchpoints', isCorrect: true }, { id: 'b', text: 'Partial conversion tracking', isCorrect: false }, { id: 'c', text: 'Fractured customer journeys', isCorrect: false }, { id: 'd', text: 'Incomplete attribution data', isCorrect: false }]), explanation: 'Fractional attribution divides conversion credit as fractions across multiple touchpoints based on their relative contribution to the conversion.', order: 163, points: 10 },
    { id: 'attribution_q10', quizId: 'quiz-attribution', text: 'What is data-driven attribution?', options: JSON.stringify([{ id: 'a', text: 'Using machine learning to determine credit based on actual conversion data', isCorrect: true }, { id: 'b', text: 'Attribution using big data', isCorrect: false }, { id: 'c', text: 'Data-based decision making', isCorrect: false }, { id: 'd', text: 'Database-driven reporting', isCorrect: false }]), explanation: 'Data-driven attribution uses machine learning algorithms to analyze actual conversion paths and determine credit distribution based on real performance data.', order: 164, points: 10 },
    { id: 'attribution_q11', quizId: 'quiz-attribution', text: 'What is cross-channel attribution?', options: JSON.stringify([{ id: 'a', text: 'Measuring contribution of different marketing channels to conversions', isCorrect: true }, { id: 'b', text: 'Advertising across TV channels', isCorrect: false }, { id: 'c', text: 'Multi-channel broadcasting', isCorrect: false }, { id: 'd', text: 'Channel surfing analytics', isCorrect: false }]), explanation: 'Cross-channel attribution measures how different marketing channels (social, search, display, etc.) contribute to conversions.', order: 165, points: 10 },
    { id: 'attribution_q12', quizId: 'quiz-attribution', text: 'What is lift measurement?', options: JSON.stringify([{ id: 'a', text: 'Comparing outcomes between exposed and control groups to measure true ad impact', isCorrect: true }, { id: 'b', text: 'Measuring elevator advertising', isCorrect: false }, { id: 'c', text: 'Brand lift surveys only', isCorrect: false }, { id: 'd', text: 'Increase in ad prices', isCorrect: false }]), explanation: 'Lift measurement compares outcomes between users exposed to ads and a control group to isolate the true incremental impact of advertising.', order: 166, points: 10 },
    { id: 'attribution_q13', quizId: 'quiz-attribution', text: 'What is a holdout group?', options: JSON.stringify([{ id: 'a', text: 'A control group not exposed to ads for measurement purposes', isCorrect: true }, { id: 'b', text: 'Users holding out for better offers', isCorrect: false }, { id: 'c', text: 'Reserved inventory', isCorrect: false }, { id: 'd', text: 'Withheld ad budget', isCorrect: false }]), explanation: 'A holdout group is a control group of users intentionally not exposed to ads, used to measure the true incremental impact of advertising.', order: 167, points: 10 },
    { id: 'attribution_q14', quizId: 'quiz-attribution', text: 'What is ghost bidding?', options: JSON.stringify([{ id: 'a', text: 'A measurement technique where bids are tracked but not executed for control groups', isCorrect: true }, { id: 'b', text: 'Hidden auction bidding', isCorrect: false }, { id: 'c', text: 'Fake bidding activity', isCorrect: false }, { id: 'd', text: 'After-hours bidding', isCorrect: false }]), explanation: 'Ghost bidding is a measurement technique where winning bids for a control group are tracked but not executed, allowing true lift measurement.', order: 168, points: 10 },
    { id: 'attribution_q15', quizId: 'quiz-attribution', text: 'What is path to conversion?', options: JSON.stringify([{ id: 'a', text: 'The sequence of touchpoints a user encounters before converting', isCorrect: true }, { id: 'b', text: 'Website navigation path', isCorrect: false }, { id: 'c', text: 'Sales funnel stages', isCorrect: false }, { id: 'd', text: 'Customer onboarding steps', isCorrect: false }]), explanation: 'Path to conversion is the complete sequence of marketing touchpoints and interactions a user has before completing a conversion.', order: 169, points: 10 },
    
    // More Advanced Questions (170-241)
    { id: 'advanced_q26', quizId: 'quiz-advanced', text: 'What is bid request?', options: JSON.stringify([{ id: 'a', text: 'A message sent to DSPs with information about an available impression', isCorrect: true }, { id: 'b', text: 'Requesting higher bids', isCorrect: false }, { id: 'c', text: 'A bid proposal document', isCorrect: false }, { id: 'd', text: 'Asking for budget approval', isCorrect: false }]), explanation: 'A bid request is sent from SSPs/exchanges to DSPs containing information about an available impression, including user and context data.', order: 170, points: 10 },
    { id: 'advanced_q27', quizId: 'quiz-advanced', text: 'What is bid response?', options: JSON.stringify([{ id: 'a', text: 'The DSP reply containing bid price and ad creative for an impression', isCorrect: true }, { id: 'b', text: 'Responding to bid inquiries', isCorrect: false }, { id: 'c', text: 'A bidding confirmation', isCorrect: false }, { id: 'd', text: 'Auction results notification', isCorrect: false }]), explanation: 'A bid response is the DSP reply to a bid request, containing the bid price and creative to be served if the bid wins.', order: 171, points: 10 },
    { id: 'advanced_q28', quizId: 'quiz-advanced', text: 'What is QPS (Queries Per Second)?', options: JSON.stringify([{ id: 'a', text: 'The number of bid requests a system can process per second', isCorrect: true }, { id: 'b', text: 'Quality points score', isCorrect: false }, { id: 'c', text: 'Question processing speed', isCorrect: false }, { id: 'd', text: 'Queue priority system', isCorrect: false }]), explanation: 'QPS measures the volume of bid requests a system can handle per second, important for ad tech infrastructure capacity.', order: 172, points: 10 },
    { id: 'advanced_q29', quizId: 'quiz-advanced', text: 'What is timeout in RTB?', options: JSON.stringify([{ id: 'a', text: 'The maximum time allowed for DSPs to respond to bid requests', isCorrect: true }, { id: 'b', text: 'Session expiration', isCorrect: false }, { id: 'c', text: 'Campaign end time', isCorrect: false }, { id: 'd', text: 'User inactivity period', isCorrect: false }]), explanation: 'RTB timeout is the maximum time (typically 50-150ms) DSPs have to respond to bid requests before they are excluded from the auction.', order: 173, points: 10 },
    { id: 'advanced_q30', quizId: 'quiz-advanced', text: 'What is ad pod?', options: JSON.stringify([{ id: 'a', text: 'A group of video ads played in sequence during a single ad break', isCorrect: true }, { id: 'b', text: 'A podcast advertising unit', isCorrect: false }, { id: 'c', text: 'A bundle of ad creatives', isCorrect: false }, { id: 'd', text: 'A group of ad networks', isCorrect: false }]), explanation: 'An ad pod is a sequence of video advertisements played back-to-back during a single commercial break in streaming content.', order: 174, points: 10 },
    { id: 'advanced_q31', quizId: 'quiz-advanced', text: 'What is MRAID?', options: JSON.stringify([{ id: 'a', text: 'Mobile Rich Media Ad Interface Definitions - standard for mobile rich media ads', isCorrect: true }, { id: 'b', text: 'Mobile Rapid Ad Integration', isCorrect: false }, { id: 'c', text: 'Multi-format Rich Ad Development', isCorrect: false }, { id: 'd', text: 'Mobile Responsive Ad Interface', isCorrect: false }]), explanation: 'MRAID is an IAB standard that provides a common API for mobile rich media ads to communicate with mobile apps.', order: 175, points: 10 },
    { id: 'advanced_q32', quizId: 'quiz-advanced', text: 'What is OMSDK?', options: JSON.stringify([{ id: 'a', text: 'Open Measurement SDK - standard for third-party viewability measurement', isCorrect: true }, { id: 'b', text: 'Online Marketing Software Development Kit', isCorrect: false }, { id: 'c', text: 'Optimized Media Serving Development Kit', isCorrect: false }, { id: 'd', text: 'Open Media Standard Development Kit', isCorrect: false }]), explanation: 'OMSDK is an IAB Tech Lab standard that enables third-party verification vendors to measure viewability in mobile apps.', order: 176, points: 10 },
    { id: 'advanced_q33', quizId: 'quiz-advanced', text: 'What is app-ads.txt?', options: JSON.stringify([{ id: 'a', text: 'An extension of ads.txt for mobile app inventory authorization', isCorrect: true }, { id: 'b', text: 'A text file listing app advertisements', isCorrect: false }, { id: 'c', text: 'Mobile app advertising format', isCorrect: false }, { id: 'd', text: 'App store ad specifications', isCorrect: false }]), explanation: 'App-ads.txt extends the ads.txt standard to mobile apps, allowing app developers to declare authorized sellers of their inventory.', order: 177, points: 10 },
    { id: 'advanced_q34', quizId: 'quiz-advanced', text: 'What is supply chain object (schain)?', options: JSON.stringify([{ id: 'a', text: 'A data structure that provides transparency into all parties handling an impression', isCorrect: true }, { id: 'b', text: 'Retail supply chain tracking', isCorrect: false }, { id: 'c', text: 'Ad delivery chain management', isCorrect: false }, { id: 'd', text: 'Supplier relationship data', isCorrect: false }]), explanation: 'The supply chain object (schain) provides transparency by listing all parties that handled an impression from publisher to DSP.', order: 178, points: 10 },
    { id: 'advanced_q35', quizId: 'quiz-advanced', text: 'What is a vertical ad network?', options: JSON.stringify([{ id: 'a', text: 'An ad network focused on a specific industry or content category', isCorrect: true }, { id: 'b', text: 'A network for vertical banner ads', isCorrect: false }, { id: 'c', text: 'An integrated ad platform', isCorrect: false }, { id: 'd', text: 'A vertically structured organization', isCorrect: false }]), explanation: 'A vertical ad network specializes in a specific industry or content category, offering targeted access to niche audiences.', order: 179, points: 10 },
    { id: 'advanced_q36', quizId: 'quiz-advanced', text: 'What is the consumer surplus in second-price auctions?', options: JSON.stringify([{ id: 'a', text: 'The difference between the winning bid and the amount actually paid', isCorrect: true }, { id: 'b', text: 'Extra inventory available', isCorrect: false }, { id: 'c', text: 'Profit margin for publishers', isCorrect: false }, { id: 'd', text: 'Unused budget', isCorrect: false }]), explanation: 'Consumer surplus is the difference between the winning bid and the amount paid in second-price auctions (e.g., if the winning bid is $5.00 but you pay $4.01, the surplus is $0.99).', order: 180, points: 10 },
    { id: 'advanced_q37', quizId: 'quiz-advanced', text: 'What is IPTV in addressable TV advertising?', options: JSON.stringify([{ id: 'a', text: 'Internet Protocol TV - delivering television via internet connections', isCorrect: true }, { id: 'b', text: 'Interactive Public Television', isCorrect: false }, { id: 'c', text: 'Integrated Platform for TV', isCorrect: false }, { id: 'd', text: 'International Programming TV', isCorrect: false }]), explanation: 'IPTV (Internet Protocol TV) delivers television content via internet connections, enabling addressable TV capabilities like showing different ads to different viewers.', order: 181, points: 10 },
    { id: 'advanced_q38', quizId: 'quiz-advanced', text: 'What is a companion ad in audio advertising?', options: JSON.stringify([{ id: 'a', text: 'A banner that appears on screen while a user listens to audio content', isCorrect: true }, { id: 'b', text: 'A second audio ad that plays simultaneously', isCorrect: false }, { id: 'c', text: 'An ad for companion products', isCorrect: false }, { id: 'd', text: 'A backup ad in case the primary fails', isCorrect: false }]), explanation: 'Companion/banner ads are similar to display banners but appear on the screen while a user listens to audio content like podcasts or music.', order: 182, points: 10 },
    { id: 'advanced_q39', quizId: 'quiz-advanced', text: 'What is look-alike modeling in DMPs?', options: JSON.stringify([{ id: 'a', text: 'Finding new users who share characteristics with existing high-value customers', isCorrect: true }, { id: 'b', text: 'Creating identical ad campaigns', isCorrect: false }, { id: 'c', text: 'Copying competitor strategies', isCorrect: false }, { id: 'd', text: 'Designing similar ad creatives', isCorrect: false }]), explanation: 'Look-alike modeling is a DMP function that finds new users who share characteristics with existing high-value customers.', order: 183, points: 10 },
    { id: 'advanced_q40', quizId: 'quiz-advanced', text: 'What is audience extension?', options: JSON.stringify([{ id: 'a', text: 'Expanding reach to new users who match the profile of existing audiences', isCorrect: true }, { id: 'b', text: 'Making ads longer', isCorrect: false }, { id: 'c', text: 'Extending campaign duration', isCorrect: false }, { id: 'd', text: 'Increasing audience age range', isCorrect: false }]), explanation: 'Audience extension uses DMPs and data to expand reach to new users who match the profile of existing audiences.', order: 184, points: 10 },
    { id: 'advanced_q41', quizId: 'quiz-advanced', text: 'What is the main purpose of consent management platforms (CMPs)?', options: JSON.stringify([{ id: 'a', text: 'To manage user consent for cookies and data collection in compliance with privacy laws', isCorrect: true }, { id: 'b', text: 'To get consent for ad placements from publishers', isCorrect: false }, { id: 'c', text: 'To approve creative content', isCorrect: false }, { id: 'd', text: 'To manage campaign budgets', isCorrect: false }]), explanation: 'CMPs manage user consent for cookies and data collection, ensuring compliance with privacy regulations like GDPR.', order: 185, points: 10 },
    { id: 'advanced_q42', quizId: 'quiz-advanced', text: 'What is Safari ITP (Intelligent Tracking Prevention)?', options: JSON.stringify([{ id: 'a', text: 'A browser privacy feature that restricts cookie creation and access', isCorrect: true }, { id: 'b', text: 'An ad blocking extension', isCorrect: false }, { id: 'c', text: 'A tracking pixel format', isCorrect: false }, { id: 'd', text: 'A payment processing system', isCorrect: false }]), explanation: 'ITP is Safari browser privacy feature that restricts cookie creation and access, limiting third-party tracking capabilities.', order: 186, points: 10 },
    { id: 'advanced_q43', quizId: 'quiz-advanced', text: 'What is Firefox Enhanced Tracking Protection?', options: JSON.stringify([{ id: 'a', text: 'A privacy feature that blocks third-party tracking cookies by default', isCorrect: true }, { id: 'b', text: 'An ad optimization tool', isCorrect: false }, { id: 'c', text: 'A performance monitoring system', isCorrect: false }, { id: 'd', text: 'A creative enhancement feature', isCorrect: false }]), explanation: 'Enhanced Tracking Protection is Firefox privacy feature that blocks third-party tracking cookies by default.', order: 187, points: 10 },
    { id: 'advanced_q44', quizId: 'quiz-advanced', text: 'What is GAID?', options: JSON.stringify([{ id: 'a', text: 'Google Advertising ID - Google mobile advertising identifier for Android', isCorrect: true }, { id: 'b', text: 'Global Ad Inventory Database', isCorrect: false }, { id: 'c', text: 'General Analytics and Insight Dashboard', isCorrect: false }, { id: 'd', text: 'Guaranteed Ad Impression Delivery', isCorrect: false }]), explanation: 'GAID (Google Advertising ID) is Google mobile advertising identifier for Android devices, similar to Apple IDFA for iOS.', order: 188, points: 10 },
    { id: 'advanced_q45', quizId: 'quiz-advanced', text: 'What is the main challenge with automated campaign optimization?', options: JSON.stringify([{ id: 'a', text: 'It requires large amounts of high-quality data to be effective', isCorrect: true }, { id: 'b', text: 'It is too expensive for most advertisers', isCorrect: false }, { id: 'c', text: 'It only works for video campaigns', isCorrect: false }, { id: 'd', text: 'It requires constant manual intervention', isCorrect: false }]), explanation: 'Automation is only as good as the data that fuels it. Without sufficient, high-quality data, algorithms can misinterpret trends.', order: 189, points: 10 },
    { id: 'advanced_q46', quizId: 'quiz-advanced', text: 'What can optimization algorithms adjust in real-time?', options: JSON.stringify([{ id: 'a', text: 'Bids per impression, budget allocation, and creative selection', isCorrect: true }, { id: 'b', text: 'Only creative colors', isCorrect: false }, { id: 'c', text: 'Publisher payment terms', isCorrect: false }, { id: 'd', text: 'User demographics', isCorrect: false }]), explanation: 'Optimization algorithms can automatically adjust bids, reallocate budgets to better-performing segments, and serve the best creative.', order: 190, points: 10 },
    { id: 'advanced_q47', quizId: 'quiz-advanced', text: 'What is invalid traffic (IVT) in ad verification?', options: JSON.stringify([{ id: 'a', text: 'Traffic generated by bots or other fraudulent sources rather than real humans', isCorrect: true }, { id: 'b', text: 'Traffic from blocked countries', isCorrect: false }, { id: 'c', text: 'Traffic during non-business hours', isCorrect: false }, { id: 'd', text: 'Traffic that does not convert', isCorrect: false }]), explanation: 'Invalid traffic refers to impressions, clicks, or conversions generated by bots or other fraudulent sources rather than real humans.', order: 191, points: 10 },
    { id: 'advanced_q48', quizId: 'quiz-advanced', text: 'What is brand safety in ad verification?', options: JSON.stringify([{ id: 'a', text: 'Ensuring ads do not appear next to illegal or offensive content', isCorrect: true }, { id: 'b', text: 'Protecting brand logos from theft', isCorrect: false }, { id: 'c', text: 'Securing payment information', isCorrect: false }, { id: 'd', text: 'Preventing competitor ad copying', isCorrect: false }]), explanation: 'Brand safety ensures ads do not appear next to questionable content such as illegal or offensive material.', order: 192, points: 10 },
    { id: 'advanced_q49', quizId: 'quiz-advanced', text: 'What is the main advantage of server-side header bidding over client-side?', options: JSON.stringify([{ id: 'a', text: 'Reduced page-load latency with a single server call', isCorrect: true }, { id: 'b', text: 'Higher cookie-matching rates', isCorrect: false }, { id: 'c', text: 'More transparency', isCorrect: false }, { id: 'd', text: 'Lower implementation costs', isCorrect: false }]), explanation: 'Server-side header bidding main advantage is reduced page-load latency because it makes a single server call instead of multiple browser requests.', order: 193, points: 10 },
    { id: 'advanced_q50', quizId: 'quiz-advanced', text: 'What is the main disadvantage of server-side header bidding?', options: JSON.stringify([{ id: 'a', text: 'Harder cookie matching and less transparency into pricing and demand', isCorrect: true }, { id: 'b', text: 'It is always slower than client-side', isCorrect: false }, { id: 'c', text: 'It cannot handle video ads', isCorrect: false }, { id: 'd', text: 'It only works on desktop', isCorrect: false }]), explanation: 'Server-side header bidding has harder cookie matching and less control and transparency into pricing and demand sources.', order: 194, points: 10 },
    { id: 'advanced_q51', quizId: 'quiz-advanced', text: 'What is a Deal ID in Private Marketplaces?', options: JSON.stringify([{ id: 'a', text: 'A unique identifier that allows advertisers to bid on premium inventory before it hits the open market', isCorrect: true }, { id: 'b', text: 'A discount code for ad inventory', isCorrect: false }, { id: 'c', text: 'A user identification number', isCorrect: false }, { id: 'd', text: 'A creative file reference', isCorrect: false }]), explanation: 'Deal IDs are unique identifiers that allow advertisers to bid on premium inventory in Private Marketplaces before it reaches the open market.', order: 195, points: 10 },
    { id: 'advanced_q52', quizId: 'quiz-advanced', text: 'What is data enrichment in a DMP?', options: JSON.stringify([{ id: 'a', text: 'Adding additional data points like geolocation and browser attributes to collected data', isCorrect: true }, { id: 'b', text: 'Making data more expensive', isCorrect: false }, { id: 'c', text: 'Increasing data storage capacity', isCorrect: false }, { id: 'd', text: 'Encrypting sensitive information', isCorrect: false }]), explanation: 'Data enrichment improves data value by adding additional data points such as geolocation, OS/browser attributes, and contextual information.', order: 196, points: 10 },
    { id: 'advanced_q53', quizId: 'quiz-advanced', text: 'What is PII in data management?', options: JSON.stringify([{ id: 'a', text: 'Personally Identifiable Information - data that can identify a specific individual', isCorrect: true }, { id: 'b', text: 'Publisher Inventory Index', isCorrect: false }, { id: 'c', text: 'Platform Integration Interface', isCorrect: false }, { id: 'd', text: 'Premium Inventory Indicator', isCorrect: false }]), explanation: 'PII includes data like email addresses, names, and physical addresses that can identify a specific individual and must be protected.', order: 197, points: 10 },
    { id: 'advanced_q54', quizId: 'quiz-advanced', text: 'What is hashing in data privacy?', options: JSON.stringify([{ id: 'a', text: 'Converting data like email addresses into encrypted strings to protect privacy', isCorrect: true }, { id: 'b', text: 'Tagging data with keywords', isCorrect: false }, { id: 'c', text: 'Organizing data into categories', isCorrect: false }, { id: 'd', text: 'Deleting old data', isCorrect: false }]), explanation: 'Hashing converts identifiable information like emails into encrypted strings, protecting privacy while still allowing data matching.', order: 198, points: 10 },
    { id: 'advanced_q55', quizId: 'quiz-advanced', text: 'What is viewability measurement?', options: JSON.stringify([{ id: 'a', text: 'Determining whether an ad was actually visible to a user, not just served', isCorrect: true }, { id: 'b', text: 'Measuring how many people view a website', isCorrect: false }, { id: 'c', text: 'Calculating total impressions', isCorrect: false }, { id: 'd', text: 'Tracking video completion rates', isCorrect: false }]), explanation: 'Viewability measurement determines whether an ad was actually visible to a user rather than just being served by the ad server.', order: 199, points: 10 },
    { id: 'advanced_q56', quizId: 'quiz-advanced', text: 'What is an SDK in mobile advertising?', options: JSON.stringify([{ id: 'a', text: 'Software Development Kit - code integrated into apps to enable ad serving and tracking', isCorrect: true }, { id: 'b', text: 'Standard Data Key', isCorrect: false }, { id: 'c', text: 'Secure Download Kit', isCorrect: false }, { id: 'd', text: 'System Design Kit', isCorrect: false }]), explanation: 'SDK (Software Development Kit) is code that app developers integrate to enable ad serving, tracking, and data collection in mobile apps.', order: 200, points: 10 },
    { id: 'advanced_q57', quizId: 'quiz-advanced', text: 'What is the difference between pre-roll, mid-roll, and post-roll video ads?', options: JSON.stringify([{ id: 'a', text: 'Pre-roll plays before content, mid-roll during content, post-roll after content', isCorrect: true }, { id: 'b', text: 'They refer to different video quality levels', isCorrect: false }, { id: 'c', text: 'They indicate different pricing models', isCorrect: false }, { id: 'd', text: 'They describe video file formats', isCorrect: false }]), explanation: 'Pre-roll video ads play before the main content, mid-roll ads play during breaks, and post-roll ads play after the content ends.', order: 201, points: 10 },
    { id: 'advanced_q58', quizId: 'quiz-advanced', text: 'What is an interstitial ad?', options: JSON.stringify([{ id: 'a', text: 'A full-screen ad that appears between content transitions, often in mobile apps', isCorrect: true }, { id: 'b', text: 'An ad that appears in the middle of articles', isCorrect: false }, { id: 'c', text: 'A small banner ad', isCorrect: false }, { id: 'd', text: 'A video ad that can be skipped', isCorrect: false }]), explanation: 'Interstitial ads are full-screen advertisements that appear at natural transition points in an app or website.', order: 202, points: 10 },
    { id: 'advanced_q59', quizId: 'quiz-advanced', text: 'What is the main purpose of A/B testing in advertising?', options: JSON.stringify([{ id: 'a', text: 'To test different ad creatives or strategies to determine which performs better', isCorrect: true }, { id: 'b', text: 'To test server capacity', isCorrect: false }, { id: 'c', text: 'To verify payment processing', isCorrect: false }, { id: 'd', text: 'To compare two different advertisers', isCorrect: false }]), explanation: 'A/B testing compares two versions of an ad creative or strategy to determine which one performs better based on metrics.', order: 203, points: 10 },
    { id: 'advanced_q60', quizId: 'quiz-advanced', text: 'What does "above the fold" mean in web advertising?', options: JSON.stringify([{ id: 'a', text: 'Ad placements visible without scrolling down the page', isCorrect: true }, { id: 'b', text: 'Premium priced inventory', isCorrect: false }, { id: 'c', text: 'Ads placed in the header section of code', isCorrect: false }, { id: 'd', text: 'Ads that float on top of content', isCorrect: false }]), explanation: 'Above the fold refers to ad placements visible in the browser window without scrolling down, typically commanding higher CPMs.', order: 204, points: 10 },
    { id: 'advanced_q61', quizId: 'quiz-advanced', text: 'What is an insertion order (IO) in advertising?', options: JSON.stringify([{ id: 'a', text: 'A contract between advertiser and publisher detailing campaign terms and pricing', isCorrect: true }, { id: 'b', text: 'The order in which ads are displayed', isCorrect: false }, { id: 'c', text: 'A command to insert tracking pixels', isCorrect: false }, { id: 'd', text: 'The sequence of bidders in an auction', isCorrect: false }]), explanation: 'An insertion order is a formal agreement between advertiser and publisher that details campaign specifications, pricing, and terms.', order: 205, points: 10 },
    
    // Extra Basics Questions (206-208)
    { id: 'basics_q12', quizId: 'quiz-basics', text: 'What is the main difference between an impression and a viewable impression?', options: JSON.stringify([{ id: 'a', text: 'A viewable impression confirms the ad was actually seen by a real human', isCorrect: true }, { id: 'b', text: 'A viewable impression costs more', isCorrect: false }, { id: 'c', text: 'A viewable impression only counts video ads', isCorrect: false }, { id: 'd', text: 'There is no difference', isCorrect: false }]), explanation: 'While an impression is counted each time a creative is served, a viewable impression specifically determines whether it was actually seen.', order: 206, points: 10 },
    { id: 'basics_q13', quizId: 'quiz-basics', text: 'Why does the AdTech industry use CPM instead of cost per single impression?', options: JSON.stringify([{ id: 'a', text: 'Because the price per impression is very small and would be inconvenient for accounting', isCorrect: true }, { id: 'b', text: 'Because it is required by law', isCorrect: false }, { id: 'c', text: 'Because advertisers prefer larger numbers', isCorrect: false }, { id: 'd', text: 'Because impressions cannot be counted individually', isCorrect: false }]), explanation: 'The industry uses thousands instead of individual impressions because the price per impression is very small.', order: 207, points: 10 },
    { id: 'basics_q14', quizId: 'quiz-basics', text: 'What is the primary goal of a landing page?', options: JSON.stringify([{ id: 'a', text: 'To drive conversions by getting users to complete a specific action', isCorrect: true }, { id: 'b', text: 'To provide general company information', isCorrect: false }, { id: 'c', text: 'To display as many ads as possible', isCorrect: false }, { id: 'd', text: 'To rank highly in search engines', isCorrect: false }]), explanation: 'Landing pages are built with a single objective: driving conversions through purchases, sign-ups, or form submissions.', order: 208, points: 10 },
    
    // Extra Technology Questions (209-217)
    { id: 'tech_q16', quizId: 'quiz-technology', text: 'What is the main difference between a DSP and an SSP?', options: JSON.stringify([{ id: 'a', text: 'DSPs serve advertisers to buy inventory; SSPs serve publishers to sell inventory', isCorrect: true }, { id: 'b', text: 'DSPs are more expensive than SSPs', isCorrect: false }, { id: 'c', text: 'DSPs only work with video ads', isCorrect: false }, { id: 'd', text: 'There is no real difference', isCorrect: false }]), explanation: 'DSPs allow advertisers to buy inventory, while SSPs help publishers manage and sell their ad inventory.', order: 209, points: 10 },
    { id: 'tech_q17', quizId: 'quiz-technology', text: 'What key integrations do DSPs typically have?', options: JSON.stringify([{ id: 'a', text: 'SSPs, ad exchanges, CDPs, DMPs, and ad verification platforms', isCorrect: true }, { id: 'b', text: 'Only social media platforms', isCorrect: false }, { id: 'c', text: 'Only payment processors', isCorrect: false }, { id: 'd', text: 'Only creative design tools', isCorrect: false }]), explanation: 'DSPs integrate with SSPs and ad exchanges (for inventory), CDPs and DMPs (for data), and ad verification platforms.', order: 210, points: 10 },
    { id: 'tech_q18', quizId: 'quiz-technology', text: 'What is a meta-DSP?', options: JSON.stringify([{ id: 'a', text: 'A platform that aggregates access to multiple DSPs through a single interface', isCorrect: true }, { id: 'b', text: 'A DSP owned by Meta (Facebook)', isCorrect: false }, { id: 'c', text: 'A premium version of a DSP', isCorrect: false }, { id: 'd', text: 'A DSP that only serves metadata', isCorrect: false }]), explanation: 'A meta-DSP provides access to multiple DSPs through a single interface, allowing management across different DSPs.', order: 211, points: 10 },
    { id: 'tech_q19', quizId: 'quiz-technology', text: 'What does header bidding support in SSPs?', options: JSON.stringify([{ id: 'a', text: 'Both client-side and server-side implementations to increase competition and yield', isCorrect: true }, { id: 'b', text: 'Only mobile advertising', isCorrect: false }, { id: 'c', text: 'Only video advertising', isCorrect: false }, { id: 'd', text: 'Only direct deals', isCorrect: false }]), explanation: 'SSPs support both client-side and server-side header bidding to increase competition and maximize publisher yield.', order: 212, points: 10 },
    { id: 'tech_q20', quizId: 'quiz-technology', text: 'What is dynamic floor pricing in SSPs?', options: JSON.stringify([{ id: 'a', text: 'Automatically adjusting minimum CPM prices based on real-time demand', isCorrect: true }, { id: 'b', text: 'Setting a single fixed price for all inventory', isCorrect: false }, { id: 'c', text: 'Pricing based on creative file size', isCorrect: false }, { id: 'd', text: 'Random price adjustments', isCorrect: false }]), explanation: 'Dynamic floor pricing allows SSPs to automatically adjust minimum CPM prices in response to real-time demand.', order: 213, points: 10 },
    { id: 'tech_q21', quizId: 'quiz-technology', text: 'What is the main use case for DMPs?', options: JSON.stringify([{ id: 'a', text: 'Improving targeting for online media campaigns and audience extension', isCorrect: true }, { id: 'b', text: 'Serving advertisements directly', isCorrect: false }, { id: 'c', text: 'Creating ad creatives', isCorrect: false }, { id: 'd', text: 'Processing payments', isCorrect: false }]), explanation: 'Main DMP use cases include improving targeting for campaigns, audience extension, and onsite personalization.', order: 214, points: 10 },
    { id: 'tech_q22', quizId: 'quiz-technology', text: 'How does a DMP create audiences?', options: JSON.stringify([{ id: 'a', text: 'By collecting event data, building user profiles, and grouping users with shared characteristics', isCorrect: true }, { id: 'b', text: 'By randomly selecting users', isCorrect: false }, { id: 'c', text: 'By purchasing pre-made lists', isCorrect: false }, { id: 'd', text: 'By surveying users directly', isCorrect: false }]), explanation: 'DMPs collect event data, normalize and enrich it, build profiles, then create audiences by grouping users based on shared characteristics.', order: 215, points: 10 },
    { id: 'tech_q23', quizId: 'quiz-technology', text: 'What key platforms do DMPs integrate with?', options: JSON.stringify([{ id: 'a', text: 'DSPs, SSPs, CRM systems, analytics platforms, and data warehouses', isCorrect: true }, { id: 'b', text: 'Only email marketing tools', isCorrect: false }, { id: 'c', text: 'Only social media platforms', isCorrect: false }, { id: 'd', text: 'Only payment processors', isCorrect: false }]), explanation: 'DMPs integrate with advertising platforms, CRM systems, marketing automation, analytics, and data warehouses.', order: 216, points: 10 },
    { id: 'tech_q24', quizId: 'quiz-technology', text: 'What is the difference between ad trafficking and AdOps?', options: JSON.stringify([{ id: 'a', text: 'Ad trafficking is the process; AdOps are the people who do it', isCorrect: true }, { id: 'b', text: 'They are exactly the same thing', isCorrect: false }, { id: 'c', text: 'AdOps is automated; ad trafficking is manual', isCorrect: false }, { id: 'd', text: 'Ad trafficking is for publishers only', isCorrect: false }]), explanation: 'Ad trafficking refers to the process of setting up and optimizing campaigns, while AdOps refers to the people responsible.', order: 217, points: 10 },
    
    // Extra Mediums Questions (218-225)
    { id: 'mediums_q17', quizId: 'quiz-mediums', text: 'What must native ads be labeled with despite blending in?', options: JSON.stringify([{ id: 'a', text: 'A disclaimer like "Sponsored" or "Paid Advertisement"', isCorrect: true }, { id: 'b', text: 'The advertiser full contact information', isCorrect: false }, { id: 'c', text: 'A warning label', isCorrect: false }, { id: 'd', text: 'Nothing - they can blend completely', isCorrect: false }]), explanation: 'Despite their integrated appearance, native ads must include a clear disclaimer indicating they are paid advertisements.', order: 218, points: 10 },
    { id: 'mediums_q18', quizId: 'quiz-mediums', text: 'What is branded/native content advertising?', options: JSON.stringify([{ id: 'a', text: 'Sponsored content hosted directly on the publisher site, developed collaboratively', isCorrect: true }, { id: 'b', text: 'Standard banner ads with brand logos', isCorrect: false }, { id: 'c', text: 'Video ads from brands', isCorrect: false }, { id: 'd', text: 'Social media posts', isCorrect: false }]), explanation: 'Branded content is hosted directly on the publisher site and developed collaboratively between brand and editorial team.', order: 219, points: 10 },
    { id: 'mediums_q19', quizId: 'quiz-mediums', text: 'What are the three main formats mentioned for rich media ads?', options: JSON.stringify([{ id: 'a', text: 'Expandable ads, interstitials, and video sliders', isCorrect: true }, { id: 'b', text: 'Text, image, and video', isCorrect: false }, { id: 'c', text: 'Banner, sidebar, and footer', isCorrect: false }, { id: 'd', text: 'Mobile, desktop, and tablet', isCorrect: false }]), explanation: 'Examples of rich media ads include expandable ads, interstitials, video sliders, AR/3D ads, and gamified advertising.', order: 220, points: 10 },
    { id: 'mediums_q20', quizId: 'quiz-mediums', text: 'What is the main characteristic of DOOH advertising?', options: JSON.stringify([{ id: 'a', text: 'It uses digital screens in public spaces with dynamic content capabilities', isCorrect: true }, { id: 'b', text: 'It only works indoors', isCorrect: false }, { id: 'c', text: 'It requires user interaction', isCorrect: false }, { id: 'd', text: 'It is cheaper than traditional billboards', isCorrect: false }]), explanation: 'DOOH leverages digital screens in high-traffic public spaces and delivers dynamic content with advanced targeting.', order: 221, points: 10 },
    { id: 'mediums_q21', quizId: 'quiz-mediums', text: 'According to the IAB Tech Lab, which devices are NOT considered CTV?', options: JSON.stringify([{ id: 'a', text: 'Desktop computers, laptops, smartphones, and tablets', isCorrect: true }, { id: 'b', text: 'Smart TVs and gaming consoles', isCorrect: false }, { id: 'c', text: 'Streaming devices like Roku', isCorrect: false }, { id: 'd', text: 'Apple TV and Fire TV', isCorrect: false }]), explanation: 'The IAB Tech Lab does not consider desktop computers, laptops, smartphones, and tablets as CTV.', order: 222, points: 10 },
    { id: 'mediums_q22', quizId: 'quiz-mediums', text: 'What advantages does Advanced TV advertising have over traditional TV?', options: JSON.stringify([{ id: 'a', text: 'Precise targeting, improved attribution, and detailed measurement', isCorrect: true }, { id: 'b', text: 'Only lower costs', isCorrect: false }, { id: 'c', text: 'Only larger audiences', isCorrect: false }, { id: 'd', text: 'No advantages', isCorrect: false }]), explanation: 'Advanced TV formats provide precise targeting, improved attribution, and detailed measurement capabilities.', order: 223, points: 10 },
    { id: 'mediums_q23', quizId: 'quiz-mediums', text: 'How does AI improve video and CTV advertising?', options: JSON.stringify([{ id: 'a', text: 'By analyzing viewer habits and enabling dynamic ad insertion with contextual targeting', isCorrect: true }, { id: 'b', text: 'By creating all video content automatically', isCorrect: false }, { id: 'c', text: 'By eliminating the need for ad servers', isCorrect: false }, { id: 'd', text: 'By making all ads free', isCorrect: false }]), explanation: 'AI enhances video/CTV by analyzing viewer habits, enabling dynamic ad insertion, and using ML for contextual targeting.', order: 224, points: 10 },
    { id: 'mediums_q24', quizId: 'quiz-mediums', text: 'What role does AI play in mobile advertising?', options: JSON.stringify([{ id: 'a', text: 'Improved location-based targeting, app usage analysis, and in-app behavioral insights', isCorrect: true }, { id: 'b', text: 'Only battery optimization', isCorrect: false }, { id: 'c', text: 'Only network speed improvement', isCorrect: false }, { id: 'd', text: 'Only app development', isCorrect: false }]), explanation: 'Mobile advertising benefits from AI through improved location-based targeting, app usage analysis, and behavioral insights.', order: 225, points: 10 },
    
    // Extra Ad Serving Questions (226-230)
    { id: 'adserving_q13', quizId: 'quiz-adserving', text: 'What information is typically passed in an ad request?', options: JSON.stringify([{ id: 'a', text: 'User location, device type, browser, content, and cookie/user ID data', isCorrect: true }, { id: 'b', text: 'Only the publisher name', isCorrect: false }, { id: 'c', text: 'Only the user email address', isCorrect: false }, { id: 'd', text: 'Only the ad slot size', isCorrect: false }]), explanation: 'Ad requests contain contextual and technical information including location, device type, browser, content, and user ID data.', order: 226, points: 10 },
    { id: 'adserving_q14', quizId: 'quiz-adserving', text: 'What happens during the ad selection logic stage?', options: JSON.stringify([{ id: 'a', text: 'The server applies rules and targeting criteria to select the best-fitting ad', isCorrect: true }, { id: 'b', text: 'The user selects which ad they want to see', isCorrect: false }, { id: 'c', text: 'Ads are selected randomly', isCorrect: false }, { id: 'd', text: 'The highest bidder always wins', isCorrect: false }]), explanation: 'During ad selection, the server applies business rules, reviews campaigns, applies filters, and selects the best-fitting ad.', order: 227, points: 10 },
    { id: 'adserving_q15', quizId: 'quiz-adserving', text: 'Where are media assets typically stored for fast ad delivery?', options: JSON.stringify([{ id: 'a', text: 'Content Delivery Networks (CDNs)', isCorrect: true }, { id: 'b', text: 'On the user device', isCorrect: false }, { id: 'c', text: 'In email servers', isCorrect: false }, { id: 'd', text: 'On physical hard drives', isCorrect: false }]), explanation: 'Media assets may be pulled from a CDN to ensure fast delivery, with ads displayed within milliseconds.', order: 228, points: 10 },
    { id: 'adserving_q16', quizId: 'quiz-adserving', text: 'What data does the tracking system continuously log?', options: JSON.stringify([{ id: 'a', text: 'Impressions, clicks, conversions, viewability, and engagement metrics', isCorrect: true }, { id: 'b', text: 'Only clicks', isCorrect: false }, { id: 'c', text: 'Only conversions', isCorrect: false }, { id: 'd', text: 'Only page views', isCorrect: false }]), explanation: 'The tracking system logs impressions, clicks, conversions, viewability, and engagement metrics for reports.', order: 229, points: 10 },
    { id: 'adserving_q17', quizId: 'quiz-adserving', text: 'What is the purpose of the inventory management system in an ad server?', options: JSON.stringify([{ id: 'a', text: 'To track available ad spaces and organize placements by format, location, and priority', isCorrect: true }, { id: 'b', text: 'To create new ad creatives', isCorrect: false }, { id: 'c', text: 'To process payments', isCorrect: false }, { id: 'd', text: 'To recruit advertisers', isCorrect: false }]), explanation: 'The inventory system manages ad spaces by tracking availability, organizing placements, and matching them to qualified campaigns.', order: 230, points: 10 },
    
    // Extra Targeting Questions (231-240)
    { id: 'targeting_q16', quizId: 'quiz-targeting', text: 'How can keywords be extracted from webpages for contextual targeting?', options: JSON.stringify([{ id: 'a', text: 'Through editor tags or by using JavaScript/server-side web crawling', isCorrect: true }, { id: 'b', text: 'Only through manual input', isCorrect: false }, { id: 'c', text: 'By analyzing user behavior', isCorrect: false }, { id: 'd', text: 'Through image recognition', isCorrect: false }]), explanation: 'Keywords can be identified via editor tags or by extracting keywords from the page using JavaScript or server-side crawling.', order: 231, points: 10 },
    { id: 'targeting_q17', quizId: 'quiz-targeting', text: 'Why might advertisers target specific ad slots and positions?', options: JSON.stringify([{ id: 'a', text: 'To control ad size and placement location for better visibility', isCorrect: true }, { id: 'b', text: 'Because it is required by law', isCorrect: false }, { id: 'c', text: 'To save money only', isCorrect: false }, { id: 'd', text: 'To avoid competition', isCorrect: false }]), explanation: 'Advertisers may choose specific ad slots and positions to ensure appropriate sizing and maximize visibility.', order: 232, points: 10 },
    { id: 'targeting_q18', quizId: 'quiz-targeting', text: 'How does GPS data improve geolocation targeting in mobile apps?', options: JSON.stringify([{ id: 'a', text: 'By providing exact longitude/latitude coordinates for radius-based targeting', isCorrect: true }, { id: 'b', text: 'By making ads load faster', isCorrect: false }, { id: 'c', text: 'By reducing data costs', isCorrect: false }, { id: 'd', text: 'GPS does not improve geolocation', isCorrect: false }]), explanation: 'Native mobile apps can provide precise GPS coordinates, allowing targeting users within a radius of a certain point.', order: 233, points: 10 },
    { id: 'targeting_q19', quizId: 'quiz-targeting', text: 'What type of data is included in behavioral targeting?', options: JSON.stringify([{ id: 'a', text: 'Event data like page views, products viewed, time on site, and purchases', isCorrect: true }, { id: 'b', text: 'Only demographic information', isCorrect: false }, { id: 'c', text: 'Only location data', isCorrect: false }, { id: 'd', text: 'Only device type', isCorrect: false }]), explanation: 'Behavioral targeting collects event data including pages viewed, search terms, time on site, clicks, and purchases.', order: 234, points: 10 },
    { id: 'targeting_q20', quizId: 'quiz-targeting', text: 'How does retargeting work technically?', options: JSON.stringify([{ id: 'a', text: 'By placing a pixel that sets a cookie, then recognizing that cookie on other sites', isCorrect: true }, { id: 'b', text: 'By following users with GPS', isCorrect: false }, { id: 'c', text: 'By reading user emails', isCorrect: false }, { id: 'd', text: 'By guessing user interests', isCorrect: false }]), explanation: 'Retargeting embeds a 1×1 pixel that places a cookie, then the DSP recognizes the cookie on other sites.', order: 235, points: 10 },
    { id: 'targeting_q21', quizId: 'quiz-targeting', text: 'What is cookie syncing used for in retargeting?', options: JSON.stringify([{ id: 'a', text: 'To recognize visitors across different websites by mapping cookie IDs between platforms', isCorrect: true }, { id: 'b', text: 'To sync cookie expiration dates', isCorrect: false }, { id: 'c', text: 'To backup cookies', isCorrect: false }, { id: 'd', text: 'To delete old cookies', isCorrect: false }]), explanation: 'DSPs use cookie syncing to recognize the same visitors across different websites by mapping user IDs between platforms.', order: 236, points: 10 },
    { id: 'targeting_q22', quizId: 'quiz-targeting', text: 'Why is demographic targeting challenging on independent platforms?', options: JSON.stringify([{ id: 'a', text: 'Most publishers do not collect demographic data directly from visitors', isCorrect: true }, { id: 'b', text: 'It is illegal to use demographics', isCorrect: false }, { id: 'c', text: 'Demographics change too frequently', isCorrect: false }, { id: 'd', text: 'It is too expensive', isCorrect: false }]), explanation: 'Demographic targeting is challenging because most publishers do not collect this data directly from visitors.', order: 237, points: 10 },
    { id: 'targeting_q23', quizId: 'quiz-targeting', text: 'How is demographic targeting applied in independent AdTech platforms?', options: JSON.stringify([{ id: 'a', text: 'Using audience segments from DMPs or demographic data in OpenRTB bid requests', isCorrect: true }, { id: 'b', text: 'By asking users to fill out surveys', isCorrect: false }, { id: 'c', text: 'Through social security numbers', isCorrect: false }, { id: 'd', text: 'It cannot be applied', isCorrect: false }]), explanation: 'On independent platforms, advertisers use audience segments from DMPs or demographic data in OpenRTB bid requests.', order: 238, points: 10 },
    { id: 'targeting_q24', quizId: 'quiz-targeting', text: 'What is ad waste?', options: JSON.stringify([{ id: 'a', text: 'Paid impressions that fail to reach the intended audience due to fraud, low viewability, or mistargeting', isCorrect: true }, { id: 'b', text: 'Unused ad creative files', isCorrect: false }, { id: 'c', text: 'Leftover budget at campaign end', isCorrect: false }, { id: 'd', text: 'Deleted ad campaigns', isCorrect: false }]), explanation: 'Ad waste refers to paid impressions that fail to reach the intended audience due to fraud, low viewability, or mistargeting.', order: 239, points: 10 },
    { id: 'targeting_q25', quizId: 'quiz-targeting', text: 'What might happen if platforms add a percentage to the daily budget cap?', options: JSON.stringify([{ id: 'a', text: 'It can compensate for under-delivery but may lead to premature budget depletion', isCorrect: true }, { id: 'b', text: 'It always saves money', isCorrect: false }, { id: 'c', text: 'It guarantees better performance', isCorrect: false }, { id: 'd', text: 'It eliminates all risk', isCorrect: false }]), explanation: 'Adding a percentage to the budget can compensate for under-delivery but may lead to premature budget depletion.', order: 240, points: 10 },
    
    // Final Tracking Question (241)
    { id: 'tracking_q16', quizId: 'quiz-tracking', text: 'What is the purpose of a 1×1 transparent image in impression tracking?', options: JSON.stringify([{ id: 'a', text: 'To send a request to the ad server when the ad is rendered, counting an impression', isCorrect: true }, { id: 'b', text: 'To display a placeholder for broken images', isCorrect: false }, { id: 'c', text: 'To test internet connection speed', isCorrect: false }, { id: 'd', text: 'To beautify the ad design', isCorrect: false }]), explanation: 'The 1×1 transparent image is loaded when the browser renders the ad, ensuring impressions are counted when ads are actually shown.', order: 241, points: 10 },
  ];

  await prisma.question.createMany({
    data: questions,
    skipDuplicates: true,
  });

  console.log(`✅ Created ${questions.length} questions (Part 2: 121-241)`);

  // Get total question count
  const totalQuestions = await prisma.question.count();
  console.log(`\n📊 Total questions in database: ${totalQuestions}`);

  console.log('\n🎉 AdTech Quiz seed (Part 2) completed!');
  console.log('\n📋 Complete Question Distribution:');
  console.log('   - Quiz: AdTech Basics (14 questions)');
  console.log('   - Quiz: AdTech Technology (24 questions)');
  console.log('   - Quiz: Advertising Mediums (24 questions)');
  console.log('   - Quiz: Ad Serving (17 questions)');
  console.log('   - Quiz: Ad Targeting & Budget (25 questions)');
  console.log('   - Quiz: Tracking & Reporting (16 questions)');
  console.log('   - Quiz: Media Buying (15 questions)');
  console.log('   - Quiz: User Identification (14 questions)');
  console.log('   - Quiz: Data in AdTech (16 questions)');
  console.log('   - Quiz: Attribution (15 questions)');
  console.log('   - Quiz: Advanced AdTech (61 questions)');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
